### ISSUE TITLE
5.0.5 esm build missing 351ba82

### ISSUE THREAD

**Issue by maunvz** [socketio/engine.io-parser#133]
The 5.0.5 release hosted at https://www.npmjs.com/package/engine.io-parser appears to be missing the changes from 351ba82
in build/esm/encodePacket.browser.js:37
        callback("b" + content);
however, build/cjs/encodePacket.browser.js:39 as the correct line:
        callback("b" + (content || ""));

**Comment by darrachequesne** [comment]
Arf, you are absolutely right, this should be fixed in [5.0.6](https://github.com/socketio/engine.io-parser/releases/tag/5.0.6).
