### ISSUE TITLE
Version 5.2.1 not available

### ISSUE THREAD

**Issue by rodrigolame** [socketio/engine.io-parser#135]
Hi, im getting an error when trying to install the version 5.2.1.

![image](https://github.com/socketio/engine.io-parser/assets/98842755/cf52eccc-0492-4486-b124-bc41e5989c6d)

Looks like that version is not published in the npm repository yet. The latest published is 5.2.0.

![image](https://github.com/socketio/engine.io-parser/assets/98842755/061f857a-21f0-4976-822b-771d16e0ff1d)

**Comment by darrachequesne** [comment]
Hi! That's weird, I'm able to see it:

```
$ npm view engine.io-parser versions
[
  '0.1.0',         '0.1.1',         '0.2.0',
  '0.2.1',         '0.3.0',         '1.0.0',
  '1.0.1',         '1.0.2',         '1.0.3',
  '1.0.4',         '1.0.5',         '1.0.6',
  '1.0.7',         '1.0.8',         '1.1.0',
  '1.2.0',         '1.2.1',         '1.2.2',
  '1.2.3',         '1.2.4',         '1.3.0',
  '1.3.1',         '1.3.2',         '2.0.0',
  '2.0.1',         '2.0.2',         '2.0.3',
  '2.1.0',         '2.1.1',         '2.1.2',
  '2.1.3',         '2.2.0',         '2.2.1',
  '4.0.0-alpha.0', '4.0.0-alpha.1', '4.0.0',
  '4.0.1',         '4.0.2',         '4.0.3',
  '5.0.0',         '5.0.1',         '5.0.2',
  '5.0.3',         '5.0.4',         '5.0.5',
  '5.0.6',         '5.0.7',         '5.1.0',
  '5.2.0',         '5.2.1'
]
```

It's on the website too: https://www.npmjs.com/package/engine.io-parser/v/5.2.1

Are you using the official NPM registry?

**Comment by darrachequesne** [comment]
Great! Thanks for the update :pray:
