### ISSUE TITLE
Unable to bundle socket.io

### ISSUE THREAD

**Issue by zecaptus** [socketio/engine.io-parser#54]
My bundle throw this error : 
`Uncaught Error: Cannot find module "engine.io-parser/keys" from "engine.io-parser"`

I use Brunch.io and Babel.

Some extract from my bundle : 
```JS
require.register('engine.io-parser', function(exports,req,module){
      var require = __makeRequire((function(n) { return req(n.replace('./', 'engine.io-parser//')); }), {}, 'engine.io-parser');
      (function(exports,require,module) {
        /**
 * Module dependencies.
 */

var keys = require('./keys');
```

if I replace here : `require('./keys')` by `require('./lib/keys')` that's work !

Or I need to replace this register by `require.register('engine.io-parser/keys',...`

```JS
require.register('engine.io-parser/lib/keys', function(exports,req,module){
      var require = __makeRequire((req), {}, 'engine.io-parser');
      (function(exports,require,module) {
        
/**
 * Gets the keys for an object.
 *
 * @return {Array} keys
 * @api private
 */

module.exports = Object.keys || function keys (obj){
  var arr = [];
  var has = Object.prototype.hasOwnProperty;

  for (var i in obj) {
    if (has.call(obj, i)) {
      arr.push(i);
    }
  }
  return arr;
};

      })(exports,require,module);
    });
```

How I can avoid this problem ?

**Comment by nkzawa** [comment]
Unfortunately, I'm not familiar with  `Brunch.io`, but it sounds it's not the problem of `engine.io-parser`.
I guess you'd need to fix your settings?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
