### ISSUE TITLE
Tag new release with #55 PR

### ISSUE THREAD

**Issue by danawoodman** [socketio/engine.io-parser#59]
In an effort to get this noticed a bit more, I am creating an issue to request the release of a new version to npm that includes the merged PR #55 so that Socket.io will work with React Native.

A few of us have been trying in vain to get an ETA on a new release but have not heard anything since April so this is a gentle effort to get a bit more love on this issue. Excuse my forwardness with this issue in advance! 😄 

CC @rauchg

**Comment by mrpatiwi** [comment]
bump

**Comment by danawoodman** [comment]
One would think after months of requests to push up a new release it might happen sometime. This is starting to get frustrating. 

@rauchg I'm sure you're a busy guy but is there any chance you or someone else on the project could push up a new release? Is there some specific reason why this or #55 haven't been addressed yet?

**Comment by danawoodman** [comment]
Obligatory monthly bump....

**Comment by razvanilin** [comment]
Would love to see this fixed too. Currently this is a stopper for developing my app. Amazed how this got fixed in a PR months ago and it never got included in a release.

So BUMP

**Comment by razvanilin** [comment]
I gave up on socket.io with RN and I'm using the standard [WebSockets](https://facebook.github.io/react-native/docs/network.html#websocket-support) now.

You can connect to a socket.io server like this

```
var socket = new WebSocket("ws://host:port/socket.io/?transport=websocket");
socket.onopen = () => {
  console.log("connected");
};
```

**Comment by danawoodman** [comment]
@razvanilin we had to do this as well. Really frustrating the lack of response from the engine.io folks on this considering they just have to run `npm publish`...

**Comment by braco** [comment]
You guys know you can npm install from a git repo, right?

**Comment by polarathene** [comment]
@braco yes it was covered in the PR comments. But do you npm install from git for all your packages? Would you feel good doing that? I don't mind doing it for one project while I wait for a release, but this has been going on since April, that's already over 6 months with no sign of the npm release ever happening.

No maintainer/collaborator responds to update us on why the update won't be pushed out, despite how active they are and how willing users are to pitch in if there is any work requried.

**Comment by chirag04** [comment]
this is a real blocker. cc @rase- @rauchg

**Comment by darrachequesne** [comment]
[v1.3.0](https://github.com/socketio/engine.io-parser/releases/tag/1.3.0) is out.

**Comment by danawoodman** [comment]
For you @darrachequesne: 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻 🍻
