### ISSUE TITLE
utf8encode

### ISSUE THREAD

**Issue by darrachequesne** [socketio/engine.io-parser#80]
A few questions:

- why are there so many public methods? Shouldn't `encodePayload` and `decodePayload` be enough?

Currently, it seems that:
    - `encodePayload/decodePayload` is used for [polling](https://github.com/socketio/engine.io/blob/1.8.2/lib/transports/polling.js#L247) transport
    - `encodePacket/decodePacket` is used for [websocket](https://github.com/socketio/engine.io/blob/1.8.2/lib/transports/websocket.js#L94) transport

Quoting https://github.com/socketio/engine.io-client/pull/140#r3404672:
> `encodePacket` is more efficient in this case so we can leverage the WS framing

Is that really more efficient? Shouldn't we rather concatenate two packets instead of sending them one by one? (I think that's why, currently, sending a buffer with socket.io results in two frames: https://github.com/socketio/socket.io/issues/2444)

- according to the following [comment](https://github.com/socketio/engine.io-parser/issues/21#issuecomment-43269500), I understand that utf8 is needed for mixing binary/string content

> The reason we are using utf8.js is that when encoding mixed binary and string contents, we need to support multibyte strings. It is easiest to encode the multibyte characters so that we can do a transformation to a binary representation one byte at a time.

Yet it seems that, since `encodePayload` always call `encodePacket` with `utf8encode` to `true`, the strings transmitted over `polling` transport are UTF8-encoded twice (https://github.com/socketio/engine.io/issues/315):

https://github.com/socketio/engine.io-parser/blob/1.3.2/lib/index.js#L229
```js
exports.encodePayload = function (packets, supportsBinary, callback) {
  ...
  if (supportsBinary) {
    return exports.encodePayloadAsBinary(packets, callback);
    // which call encodePacket with utf8encode = true => OK
  }
  ...
  function encodeOne(packet, doneCallback) {
    exports.encodePacket(packet, supportsBinary, true, function(message) {
      doneCallback(null, setLengthHeader(message));
    });
    // since the payload is not encoded as binary, shouldn't utf8encode be set to false here?
  }
}
```

cc @calzoneman @rase- @rauchg

**Comment by calzoneman** [comment]
Here are a couple interesting commits from the parser:

  * https://github.com/socketio/engine.io-parser/commit/52bc2f8c03fd453048642e607f9a05021ff1768d
  * https://github.com/socketio/engine.io-parser/commit/95840ca6b6d393d9f9140b105405809094af643b

It looks like at first, `utf8` was *always* used, "to support multibyte strings".  Later on, it was realized that `ws` is already encoding the payload, so it was made optional, but still defaults to `true` for polling transports.  This is the part that doesn't make sense to me, because with the appropriate headers set, the http server should already be handling this encoding.  I don't have the full context on the issue that prompted the addition of `utf8` "to support multibyte strings", so maybe that would be a good place to start.

**Comment by darrachequesne** [comment]
@calzoneman thanks for taking the time to look into that! If I understand correctly, I think that makes sense when mixing binary/string content in the same payload, since in that case the content type will be `application/octet-stream` (and not `text/plain; charset=UTF-8`, see [ref](https://github.com/socketio/engine.io/blob/1.8.2/lib/transports/polling.js#L282)).

**Comment by calzoneman** [comment]
That's the part that I was missing (that you can send binary data and UTF-8 string data in the same polling payload).  In that case, I guess what's happening is that for string-only payloads, they are being encoded twice (once by engine.io, and again when going over the wire).

It might get a bit messy to try to selectively encode strings depending on the payload's content-type.  This is also going to be a backwards-incompatible change for any client code using the polling transport.  Not sure what the best solution is here.

**Comment by darrachequesne** [comment]
What do you think of https://github.com/socketio/engine.io-parser/pull/81? Does it make sense to skip utf8 encoding when dealing with payloads without binary content?

**Comment by calzoneman** [comment]
+ @nuclearace since he was actually the first person to point out the double encoding to me.

**Comment by nuclearace** [comment]
Yeah, I'll need to change some stuff on the Swift client if things stop getting double encoded.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-parser/pull/81 (will trigger a major release)
