### ISSUE TITLE
2.0.1 has broken multi-byte characters

### ISSUE THREAD

**Issue by stephank** [socketio/engine.io-parser#87]
It appears since 2.0.1, multi-byte characters are breaking in browser clients.

In practice, we have an application that happened to send a JSON message containing a no-break space (U+00A0) somewhere, and the browser client received the message with the final `}` cut-off.

With a normal install of `engine.io-client@2.1.0`, zuul tests also fail there. When the `engine.io-parser` dep is then replaced with 2.0.0 (by simply swapping the directory in `node_modules`), tests succeed again.

All tests seem to work fine in Node.js.

(macOS 10.12.3, Chrome 56.0.2924.87. Same results in Firefox 52.0.)

**Comment by darrachequesne** [comment]
Thanks for the report. It seems to be related with https://github.com/socketio/engine.io-parser/pull/85.

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/engine.io-parser/pull/88 and https://github.com/socketio/engine.io-client/pull/555.

**Comment by stephank** [comment]
Awesome, thanks! :)
